---
title: "Publications"
draft: false
---

[Google Scholar](https://scholar.google.com/citations?user=HGu73BYAAAAJ&hl=en)

# 2021
---

**Unravel: A Fluent Code Explorer for Data Wrangling.** Nischal Shrestha, Titus Barik and Chris Parnin. To appear in *UIST 2021: 34th ACM Symposium on User Interface Software and Technology* 

[[DOI](https://doi.org/10.1145/3472749.3474744) | [PDF](http://nischalshrestha.me/docs/unravel.pdf) | [Talk](https://www.youtube.com/watch?v=wJ77e39XVEs)]

> We built a tool called Unravel to help data scientists understand and explore fluent code via structured edits using drag-and-drop and toggle switch interactions. Through a think-aloud user study with 14 data scientists, we found that Unravel facilitated diverse activities such as validating assumptions about the code or data, exploring alternatives, and understanding function behavior.

**Remote, but Connected: How #TidyTuesday Provides an Online Community of Practice for Data Scientists.** Nischal Shrestha, Titus Barik and Chris Parnin. *CSCW 2021: 24th ACM Conference on Computer-Supported Cooperative Work and Social Computing* 

[[DOI](https://doi.org/10.1145/3449126) | [PDF](http://nischalshrestha.me/docs/tidytuesday.pdf) | [Talk](https://youtu.be/kMm4tKKOtjU)] 

> Through semi-structured interviews with 26 data scientists, we uncovered motivations behind their participation in #TidyTuesday, how the project benefited them, and how it cultivated an online CoP.

# 2020
---

**Here We Go Again: Why Is It Difficult for Developers to Learn Another Programming Language?** Nischal Shrestha, Colton Botta, Titus Barik and Chris Parnin. *ICSE 2020: 42nd ACM/IEEE International Conference on Software Engineering.* {{< fa trophy >}} Won an [ACM SIGSOFT Distinguished Paper Award](http://nischalshrestha.me/docs/icse20award.pdf). 

[[DOI](https://doi.org/10.1145/3377811.3380352) | [PDF](http://nischalshrestha.me/docs/cross_language_interference.pdf) | [Talk](https://t.co/lK34TjFAJn?amp=1)]

> We found that previous programming language knowledge can interfere with learning another programming language.

# 2019
---

**Instrument Designs for Validating Cross-Language Behavioral Differences** Nischal Shrestha and Chris Parnin. *2019 IEEE Symposium on Visual Languages and Human-Centric Computing (VL/HCC)* 

[[DOI](https://doi.org/10.1109/VLHCC.2019.8818911) | [PDF](http://nischalshrestha.me/docs/Misconceptions_VLHCC_19.pdf)]

> We designed three instruments that can help identify and validate meaningful behavior differences between two languages to pinpoint potential misconceptions.

**Exploring Tools and Strategies Used During Regular Expression Composition Tasks** Gina R. Bai, Brian Clee, Nischal Shrestha, Carl Chapman, Cimone Wright, Kathryn T. Stolee. *2019 IEEE/ACM 27th International Conference on Program Comprehension (ICPC)* 

[[DOI](https://doi.org/10.1109/ICPC.2019.00039) | [PDF](https://ginabai.github.io/PaperPreprints/icpc2019_RegexVideo.pdf)]

> We conducted an exploratory case study to reveal the tools and strategies developers use during regular expression composition.

# 2018
---

**It's Like Python But: Towards Supporting Transfer of Programming Language Knowledge** Nischal Shrestha, Titus Barik and Chris Parnin. *2018 IEEE Symposium on Visual Languages and Human-Centric Computing (VL/HCC)* 

[[DOI](https://doi.org/10.1109/VLHCC.2018.8506508) | [PDF](http://nischalshrestha.me/docs/ItsLikePythonBut.pdf)]

> We explored a prototype transfer tool to support learning new programming languages, given experience in one or more languages.
